name: Create sdists package and upload it to PyPI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine
    - name: Create sdist
      run: |
        python setup.py sdist
    - name: Upload artifacts for inspection
      uses: actions/upload-artifact@v2
      with:
        name: sdist
        path: dist/*.tar.gz
    - name: Publish sdists and wheels to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/* || :
